import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';import {hand} from './fixtures.mjs';
await mkdir('artifacts',{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
const base=process.env.TEST_URL||'http://localhost:8788/';
try{
 const page=await browser.newPage({viewport:{width:1280,height:800},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/vision_bundle.mjs',route=>route.fulfill({contentType:'text/javascript',body:`export const FilesetResolver={forVisionTasks:async()=>({})};export const HandLandmarker={createFromOptions:async()=>({detectForVideo:()=>{window.fixtureDetections=(window.fixtureDetections||0)+1;return {landmarks:window.testHands||[]}},close(){}})};`}));
 await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=1280;c.height=720;const g=c.getContext('2d');function paint(){const bg=g.createLinearGradient(0,0,1280,720);bg.addColorStop(0,'#64746d');bg.addColorStop(1,'#29253a');g.fillStyle=bg;g.fillRect(0,0,1280,720);g.fillStyle='#acbaa7';g.fillRect(70,60,220,450);g.fillStyle='#d9c8b1';g.beginPath();g.ellipse(650,460,175,225,0,0,7);g.fill();g.fillStyle='#eee';g.font='20px sans-serif';g.fillText('SYNTHETIC CAMERA TEST',450,60);}paint();setInterval(paint,80);const s=c.captureStream(12);window.testStreams??=[];window.testStreams.push(s);return s;};});
 await page.goto(base);await page.evaluate(()=>{window.testHints=[];new MutationObserver(()=>window.testHints.push(document.querySelector('#hint-text').textContent)).observe(document.querySelector('#hint-text'),{childList:true,subtree:true,characterData:true});});await page.locator('#start').click();await page.waitForFunction(()=>window.fixtureDetections>0);
 assert.equal(await page.locator('#welcome').isVisible(),false);assert.equal(await page.locator('video').evaluate(e=>e.getBoundingClientRect().width),1280);
 await page.evaluate(h=>window.testHands=[h],hand());await page.waitForFunction(()=>document.querySelector('#hint-text').textContent==='Ia mekar karena hadirmu');await page.waitForTimeout(1000);await page.screenshot({path:'artifacts/palm-desktop.png'});
 await page.evaluate(h=>window.testHands=[h],hand('pinch'));await page.waitForFunction(()=>window.testHints.some(s=>s.includes('Lepaskan')));await page.evaluate(h=>window.testHands=[h],hand());await page.waitForFunction(()=>window.testHints.some(s=>s.includes('seseorang')));
 await page.evaluate(h=>window.testHands=h,[hand('open',-.15),hand('open',.15)]);await page.waitForTimeout(5500);await page.screenshot({path:'artifacts/bouquet-desktop.png'});
 const download=page.waitForEvent('download');await page.locator('#capture').click();const file=await download;assert.equal(file.suggestedFilename(),'mekar-di-tanganmu.png');await file.saveAs('artifacts/captured.png');
 await page.locator('#palette').click();await page.locator('#sound').click();assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');await page.locator('#sound').click();
 await page.locator('#help').click();assert.equal(await page.locator('#guide').isVisible(),true);await page.locator('#understood').click();
 await page.locator('#stage').click({position:{x:20,y:300}});assert.equal(await page.locator('body.clean').count(),1);await page.locator('#stage').click({position:{x:20,y:300}});
 await page.locator('#flip').click();await page.waitForFunction(()=>document.querySelector('body').classList.contains('live')&&!document.querySelector('#flip').disabled);assert.equal(await page.locator('video.rear').count(),1);assert.equal(await page.evaluate(()=>window.testStreams[0].getTracks().every(t=>t.readyState==='ended')),true);
 await page.setViewportSize({width:390,height:844});await page.evaluate(h=>window.testHands=[h],hand());await page.waitForTimeout(1200);await page.screenshot({path:'artifacts/palm-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth),true);
 await page.locator('#stop').click();assert.equal(await page.evaluate(()=>window.testStreams.every(s=>s.getTracks().every(t=>t.readyState==='ended'))),true);assert.equal(await page.locator('#welcome').isVisible(),true);
 await page.evaluate(()=>navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');});await page.locator('#start').click();await page.waitForFunction(()=>document.querySelector('#welcome-copy').textContent.includes('Izinkan'));assert.equal(await page.locator('#start').isEnabled(),true);assert.deepEqual(errors,[]);
 console.log('PASS: full-screen camera, gesture-driven effects with fixture landmarks, pinch release, bouquet, photo export, palette, audio, help, clean screen, front/rear mirror, mobile, permission denial, track cleanup.');
}finally{await browser.close();}
